# Generated by Django 5.0 on 2023-12-21 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('iswp', models.BooleanField(default=False)),
                ('search_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
