# Generated by Django 5.0 on 2024-01-08 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='collect',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='delivery',
            field=models.BooleanField(default=False),
        ),
    ]
