# Generated by Django 5.0 on 2023-12-29 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.CharField(default='kawai', max_length=70),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=90),
        ),
    ]
